### ISSUE TITLE
No CICD to validate the profile in review

### ISSUE THREAD

**Issue by aaronlippold** [mitre/microsoft-windows-server-2019-stig-baseline#11]
In order to streamline the review process, we need to have a kitchen and actions set up to build, configure and validate the profile.

**Comment by aaronlippold** [comment]
https://github.com/chef-cookbooks/windows/blob/master/kitchen.yml

**Comment by aaronlippold** [comment]
https://supermarket.chef.io/cookbooks/test_kitchen_adds

**Comment by aaronlippold** [comment]
https://github.com/TAMUArch/cookbook.windows_ad

**Comment by aaronlippold** [comment]
https://sammart.in/post/integration-testing-ad-dependent-cookbooks-and-powershell-scripts-with-test-kitchen/

**Comment by superyarick** [comment]
```https://github.com/mitre/microsoft-windows-server-2019-stig-baseline/actions/runs/309249848```

Are we looking to perform any additional validation to these actions?
