### ISSUE TITLE
V-92991 should not expect optical drives to be formatted NTFS

### ISSUE THREAD

**Issue by rdean716** [mitre/microsoft-windows-server-2019-stig-baseline#20]
Hi Maintainers,

Currently the control is using WMI to grab all instances of logical disks to ensure that they are all formatted NTFS or ReFS.  Drive type 5 is "Compact Disc" and, i think NTFS is not an appropriate expectation here.  I would propose limiting the original WMI query to only type 3 drives, or excluding type 5 drives from the results, though I think NTFS may not be appropriate for the other drive types as well.

currently:
` get_volumes = command("wmic logicaldisk get FileSystem | findstr /r /v '^$' |Findstr /v 'FileSystem'").stdout.strip.split("\r\n")`

proposed:
` get_volumes = command("wmic logicaldisk where DriveType=3 get FileSystem | findstr /r /v '^$' |Findstr /v 'FileSystem'").stdout.strip.split("\r\n")`

Will submit a PR if you concur?

**Comment by aaronlippold** [comment]
Sounds great
--------
Aaron Lippold

lippold@gmail.com

260-255-4779

twitter/aim/yahoo,etc.
'aaronlippold'
