### ISSUE TITLE
Local admin accounts with a dash (or other excluded string) in their name are excluded from evaluation

### ISSUE THREAD

**Issue by t0sche** [mitre/microsoft-windows-server-2019-stig-baseline#32]
https://github.com/mitre/microsoft-windows-server-2019-stig-baseline/blob/6d2dac5b47e6fc9e8c5489655bc9adcc3b188d67/controls/V-93043.rb#L70

Not sure what the best solution to modifying this command would be other than adding 2+ dashes to read `net localgroup Administrators | Format-List | Findstr /V 'Alias Name Comment Members -- command'`.

**Comment by rdean716** [comment]
Maybe convert it to PowerShell, like many of the other controls in this profile, and not worry about parsing the text like this?

**Comment by t0sche** [comment]
`Get-LocalGroupMember -Group "Administrators" | select -ExpandProperty Name | ForEach-Object {$_ -replace "$env:COMPUTERNAME\\" -replace ""}`

**Comment by aaronlippold** [comment]
Sounds great. Are you going to push a PR with the change?
--------
Aaron Lippold

***@***.***

260-255-4779

twitter/aim/yahoo,etc.
'aaronlippold'

**Comment by t0sche** [comment]
@aaronlippold #33
