### ISSUE TITLE
Do these check for any other SIDs?

### ISSUE THREAD

**Issue by ejaronne** [mitre/microsoft-windows-server-2019-stig-baseline#7]
https://github.com/mitre/microsoft-windows-server-2019-stig-baseline/blob/peer-review/controls/V-92995.rb 

Does this check if any SIDs other than the following are granted the
\"SeNetworkLogonRight\" user right, because this would be a finding (fail).

    S-1-5-32-544 (Administrators)
    S-1-5-11 (Authenticated Users)
    S-1-5-9 (Enterprise Domain Controllers)

RIght now it seems to only check if these 3 do have the right, but not if other SIDs do?

Similar question for V-93059, V-93069, V-93073

**Comment by karikarshivani** [comment]
Fixed by #10
