### ISSUE TITLE
Inconsistent `describe.one` blocks

### ISSUE THREAD

**Issue by karikarshivani** [mitre/microsoft-windows-server-2019-stig-baseline#75]
The `describe.one` blocks for these controls are not consistent:
- [x] V-93249
- [x] V-93261
- [x] V-93263
- [x] V-93267
- [x] V-93311
- [x] V-93413
- [x] V-93563
---
The controls listed above have this in the check text:

> If the registry value name below does not exist, this is not a finding.
> If it exists and is configured with a value of \<value\>, this is not a finding.
> If it exists and is configured with a value of \<value\>, this is a finding.
---
Code recommendation:

```
describe.one do
    describe registry_key('<path>') do
        it { should_not have_property '<property>' }
    end
    describe registry_key('<path>') do
        it { should have_property '<property>' }
        its('SaveZoneInformation') { should_not cmp <value> }
        its('SaveZoneInformation') { should cmp <value> }
    end
end
```

**Comment by abailey1021** [comment]
Describe Blocks updated... Pending review.
