### ISSUE TITLE
V-93475 fix

### ISSUE THREAD

**Issue by graybw** [mitre/microsoft-windows-server-2019-stig-baseline#76]
Add additional functionality to the control
https://github.com/mitre/microsoft-windows-server-2019-stig-baseline/pull/77

**Comment by Amndeep7** [comment]
@graybw can you please expand on what additional functionality needs to be added?

**Comment by graybw** [comment]
@Amndeep7 I have a few control fixes to submit on behalf of aagiardd, however it doesn't look like I have the rights to push my branch containing his fixes.  Is there a way you can allow me access to push my branch for review?

**Comment by aaronlippold** [comment]
Easiest way is for you to fork the repo And submit a PR
