### ISSUE TITLE
V-93283 logic reversed?

### ISSUE THREAD

**Issue by ejaronne** [mitre/microsoft-windows-server-2019-stig-baseline#8]
https://github.com/mitre/microsoft-windows-server-2019-stig-baseline/blob/peer-review/controls/V-93283.rb

"If \"NewGuestName\" is not something other than \"Guest\" in the file, this is a finding."

Yet the describe block seems to be the reverse?

```
  describe security_policy do
    its('NewGuestName') { should eq "Guest" }
  end
```
or am I misunderstanding?

**Comment by karikarshivani** [comment]
Great catch! The [control](https://github.com/mitre/microsoft-windows-server-2019-stig-baseline/blob/peer-review/controls/V-93283.rb) has now been changed to
```
describe security_policy do
  its('NewGuestName') { should_not eq "Guest" }
end
```
