### ISSUE TITLE
V-93509 parameterize \"300\" in check/fix text

### ISSUE THREAD

**Issue by ejaronne** [mitre/microsoft-windows-server-2019-stig-baseline#85]
Check and Fix text baseline has \"300\" MaxConnIdleTime specified, but this needs to be replaced with the input "maximum_idle_time" to allow overlays to display correct wording.

**Comment by karikarshivani** [comment]
Thank you! I have made that change - [commit reference](https://github.com/mitre/microsoft-windows-server-2019-stig-baseline/pull/86/commits/018d43bd50bb4df6c17070dd4dc351aa81de7c48)
