### ISSUE TITLE
Input Optimization

### ISSUE THREAD

**Issue by karikarshivani** [mitre/microsoft-windows-server-2019-stig-baseline#89]
Consider removing redundant inputs that were created to parameterize STIG text. Currently, the inputs that can be removed are:
- `temporary_account_period_phrase`
- `emergency_account_period_phrase`
- `maximum_idle_time_phrase`

These inputs can be instead calculated as needed (ex: `#{input('xphrase')/60}`)

**Comment by abailey1021** [comment]
Changes made and pushed to ab_InputOptimization89 branch for review.
